name: movies_amit63
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.4.3+1
  carousel_slider: ^4.2.1
  flutter_bloc: ^8.1.5
  flutter_widget_from_html_core: ^0.14.12
  get_it: ^7.6.7
  kiwi: ^5.0.0
  shimmer: ^3.0.0
  flutter_screenutil: ^5.9.1
  google_maps_flutter: ^2.5.3
  maps_launcher: ^2.2.1
  geocoding: ^3.0.0
  geolocator: ^11.1.0
  chart_sparkline: ^1.0.15+1
  circular_countdown_timer: ^0.2.3
  shared_preferences:
  easy_localization: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/translations/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
